% psAnalysis.m
% Script to analyze psMatrices (Preference Score) for all mice in allPsMatrices
%
% This script serves as the final step in the behavioral analysis pipeline.
% It is designed to read the `allPsMatrices.mat` file generated by the main
% analysis script, aggregate the data, and generate a series of visualizations
% to summarize the results across individual sessions, individual mice, and
% all experiments combined.
%
% The script's primary functions include:
%   1.  Aggregating preference score matrices for each mouse.
%   2.  Creating and plotting a raw sum matrix for each mouse.
%   3.  Generating a normalized average matrix per mouse.
%   4.  Plotting heatmaps to visualize the data, similar to the `oneBehaveAnalysis`
%       script.
%   5.  Creating a figure with subplots for all sessions of a single mouse,
%       including a final subplot for the mouse's overall average.
%   6.  Saving a separate, standalone figure for the average of each mouse.
%   7.  Aggregating and saving an overall average across all experiments.
%
% Special Rule for Outliers:
%   To prevent extreme values from skewing the averages, preference scores
%   that are very close to -1 or 1 are treated as outliers. These are
%   determined by a `threshold` parameter (e.g., a threshold of 0.2 means
%   values less than -0.8 or greater than 0.8 are considered outliers).
%   Outliers are displayed in white on the heatmaps but are not included
%   in any of the average calculations.
%
% ---
%
% Execution and Saving Process
%
% This script runs through a nested loop structure to process and save the
% analysis results systematically.
%
% Iteration Process:
%   - The outer loop iterates through each **unique mouse ID** found in the
%     `allPsMatrices` file.
%   - The inner loop then processes each **individual session** for the
%     current mouse. The number of times this inner loop runs depends on
%     how many experiment files were processed for each mouse.
%
% Saved Outputs and Locations:
%   The script saves several figures in different directories to organize the
%   results for easy access and comparison.
%
%   1.  **Per Mouse Session Plots:** For each unique mouse, a figure is created
%       with subplots for every single session, as well as a final plot for
%       the average across all its sessions. This figure is saved in two places:
%       - `results/3chamber/boundary&sequence/<group>/<color>/all_days.png`
%       - `results/3chamber/boundary&sequence/summary_ps/all_days/<group>_<color>_all_days.png`
%       A corresponding `.fig` file is also saved at both locations.
%
%   2.  **Per Mouse Average Plot:** A standalone figure showing only the
%       average heatmap for the mouse is created and saved in two locations:
%       - `results/3chamber/boundary&sequence/<group>/<color>/average.png`
%       - `results/3chamber/boundary&sequence/summary_ps/per_mouse/average/<group>_<color>.png`
%       A corresponding `.fig` file is also saved at both locations.
%
%   3.  **Overall Average Plot:** After processing all mice, a final figure is
%       generated that shows the grand average preference score across all
%       experiments. This figure is saved to:
%       - `results/3chamber/boundary&sequence/all_groups/average.png`
%       A corresponding `.fig` file is also saved.
%
% ---
clc, clear, close all;

% Parameters
boundaries = 0 : 0.5 : 5;     % Boundary allowances in cm
seqTimes = 0 : 0.5 : 5;       % Sequence times in seconds (minimum stay in ROI)
threshold = 0.2;              % Tolerance around ±1 to treat as outlier
modePerExp = "normalize";       % Aggregation mode: 'none', 'normalize', or 'zscore'
modePerMouse = "normalize";
baseDir = fullfile("results", "3chamber", "boundary&sequence");

% -------- Collect matrices --------
path = "results\3chamber\boundary&sequence\allPsMatrices.mat";
load(path, 'allPsMatrices');

% -------- Collect all fields --------
allFields = fieldnames(allPsMatrices);
% Extract unique mouse IDs (strip dates from field names)
mouseIDs = unique(cellfun(@(f) extractMouseID(f), allFields, 'UniformOutput', false));
% Overall aggregation storage (flexible pipeline)
allMatrices = {};

% Loop through each mouse
for m = 1:numel(mouseIDs)
    close all;
    mouseID = mouseIDs{m};
    % Erase prefix to group number (remove zv/x)
    mouseID = regexp(mouseID, '\d.*', 'match', 'once'); 
    % Filter fields belonging to this mouse
    mouseFields = allFields(contains(allFields, mouseID));
    if isempty(mouseFields)
        warning('No matrices found for mouse %s', mouseID);
        continue;
    end
    % Initialize aggregation
    sumMatrix = 0;
    nSessions = 0;

    % -------- Subplot figure for this mouse --------
    fig = figure('Color','w', 'Name', sprintf('Mouse %s - All Sessions', mouseID));
    nCols = ceil(sqrt(numel(mouseFields)+1));
    nRows = ceil((numel(mouseFields)+1) / nCols);
    
    % Loop through sessions for this mouse
    for i = 1:numel(mouseFields)
        rawMatrix = allPsMatrices.(mouseFields{i});
        
        % Apply normalization per matrix if needed
        psMatrix = preprocessMatrix(rawMatrix, threshold, modePerExp);
        sumMatrix = sumMatrix + psMatrix;
        nSessions = nSessions + 1;
        
        % Masked display matrix (for visualization only). if |value| >=
        % threshold it will be masked (white). The preprocessMatrix
        % function (above) makes sure that those values won't be account.
        displayMatrix = rawMatrix;
        mask = (rawMatrix >= (1 - threshold)) | (rawMatrix <= (-1 + threshold));
        displayMatrix(mask) = NaN;
        
        % Extract date from field name
        parts = split(mouseFields{i}, '_');
        sessionDate = parts{3};
        
        % Plot this session
        subplot(nRows, nCols, i);
        plotHeatmap(boundaries, seqTimes, displayMatrix, sessionDate);
    end

    % Avrage matrix (mouse average)
    avgMatrix = sumMatrix / nSessions;
    % Plot average in last subplot using helper function (with headline)
    subplot(nRows, nCols, numel(mouseFields)+1);
    plotAverageHeatmap(boundaries, seqTimes, avgMatrix, nSessions, true);

    % -------- Save figures --------
    parts = split(mouseID, '_');
    group = parts{1};
    color = parts{2};
    
    % Add super-title with padding to avoid overlap
    sgtitle(sprintf('%s, %s - Outliers (|value| > %.1f) shown in white, excluded from average', ...
        group, color, 1-threshold), 'FontSize', 10, 'Interpreter', 'none');
    set(findall(gcf,'Type','axes'),'TitleFontSizeMultiplier',0.9); % shrink subplot titles
    
    % ---- Save subplots (all sessions + average subplot, png and fig) ----
    % save in baseDir\group\color as all_days
    SaveFolders.saveFile([], fig, fullfile(baseDir, group, color), 'all_days', ...
        {'png', 'fig'}, false);
    % save in baseDir\summary_ps\all_days as <group>_<color>_all_days
    SaveFolders.saveFile([], fig, fullfile(baseDir, "summary_ps", "all_days"),...
        sprintf('%s_%s_all_days', group, color), {'png', 'fig'}, false);

    % -------- Save separate average-only figure (png and fig) --------
    figAvg = createAverageFigure(boundaries, seqTimes, avgMatrix, nSessions, group, color, threshold);
    % save in baseDir\group\color as average
    SaveFolders.saveFile([], figAvg, fullfile(baseDir, group, color), 'average', ...
        {'png', 'fig'}, false);
    % save in baseDir\summary_ps\per_mouse as average
    SaveFolders.saveFile([], figAvg, fullfile(baseDir, "summary_ps",...
        "per_mouse", "average"), sprintf('%s_%s', group, color), {'png', 'fig'}, false);

    % -------- Collect matrices for overall analysis --------
    avgNormMatrix = preprocessMatrix(rawMatrix, threshold, modePerMouse);
    allMatrices{end+1} = avgNormMatrix;
end

% -------- Flexible aggregation across all experiments --------
allNormMatrix = aggregateMatrices(allMatrices);
figAll = createAverageFigure(boundaries, seqTimes, allNormMatrix, numel(allMatrices), 'All', 'Experiments', threshold);

% Save overall average in baseDir\all_groups as average
SaveFolders.saveFile([], figAll, fullfile(baseDir, 'all_groups'), 'average', ...
        {'png', 'fig'}, false);

% -------- Helper functions --------
function mouseID = extractMouseID(fieldName)
    % extractMouseID - Extracts group+color from field name
    %   Input:  fieldName like 'xl0th_blue_20240321'
    %   Output: mouseID like 'xl0th_blue'
    parts = split(fieldName, '_');
    mouseID = strjoin(parts(1:2), '_');
end
function psMatrix = preprocessMatrix(rawMatrix, threshold, mode)
    % preprocessMatrix - Applies preprocessing rules to a matrix
    %   rawMatrix: the raw preference score matrix
    %   threshold: values within threshold distance from ±1 are set to 0 so
    %   it won't count to the sum mat. 
    %   mode: aggregation mode ('none', 'normalize', 'zscore')
    %   Returns: processed matrix ready for aggregation
    % Mask extreme values
    mask = (rawMatrix >= (1 - threshold)) | (rawMatrix <= (-1 + threshold));
    psMatrix = rawMatrix;
    psMatrix(mask) = 0;
    switch mode
        case 'normalize'
            % Scale matrix to [-1, 1] based on min/max (if not constant)
            minVal = min(psMatrix(:));
            maxVal = max(psMatrix(:));
            if maxVal > minVal
                psMatrix = 2 * ((psMatrix - minVal) / (maxVal - minVal)) - 1;
            end
        case 'zscore'
            % Apply z-scoring (if not constant)
            mu = mean(psMatrix(:));
            sigma = std(psMatrix(:));
            if sigma > 0
                psMatrix = (psMatrix - mu) / sigma;
            end
        case 'none'
            % Leave unchanged
    end
end
function aggMatrix = aggregateMatrices(matrixList)
    % aggregateMatrices - Aggregates a list of matrices flexibly
    %   matrixList: cell array of matrices to aggregate
    %   Returns: element-wise average across matrices.
    if isempty(matrixList)
        aggMatrix = [];
        return;
    end
    n = numel(matrixList);
    aggMatrix = 0;
    for i = 1:n
        mat = matrixList{i};
        aggMatrix = aggMatrix + mat;
    end
    aggMatrix = aggMatrix / n;
end
function plotHeatmap(boundaries, seqTimes, displayMatrix, titleText)
    % plotHeatmap - Plots a single session heatmap with masked outliers
    %   boundaries: boundary allowances
    %   seqTimes: sequence times
    %   displayMatrix: matrix with NaN for outliers
    %   titleText: title string (e.g., session date)
    h = imagesc(boundaries, seqTimes, displayMatrix);
    colormap(jet);
    colorbar;
    xlabel('Boundary (cm)');
    ylabel('Seq Time (s)');
    title(titleText, 'Interpreter', 'none', 'FontSize', 8);
    set(gca, 'YDir', 'normal');
    set(h, 'AlphaData', ~isnan(displayMatrix)); % NaNs transparent
    colormap(gca, [0 0 0; jet(256)]); % prepend black for NaN
end
function plotAverageHeatmap(boundaries, seqTimes, normMatrix, nSessions, addHeadline)
    % plotAverageHeatmap - Plots the average preference score heatmap
    %   boundaries: boundary allowances
    %   seqTimes: sequence times
    %   normMatrix: normalized matrix (average over sessions)
    %   nSessions: number of sessions included
    %   addHeadline: if true, adds a title to the plot. For subplot usage this
    %                should be true, for standalone average figure this should be false.
    imagesc(boundaries, seqTimes, normMatrix);
    colormap(jet);
    colorbar;
    xlabel('Boundary (cm)');
    ylabel('Seq Time (s)');
    if addHeadline
        title(sprintf('Average (%d sessions)', nSessions), 'FontSize', 9);
    end
    set(gca, 'YDir', 'normal');
end
function figAvg = createAverageFigure(boundaries, seqTimes, normMatrix, nSessions, group, color, threshold)
    % createAverageFigure - Creates a standalone average-only figure
    %   boundaries: boundary allowances
    %   seqTimes: sequence times
    %   normMatrix: normalized matrix (average over sessions)
    %   nSessions: number of sessions included
    %   group, color: identifiers for mouse group and color
    %   threshold: outlier threshold used for exclusion
    %   Output: a figure handle containing the average heatmap
    %   Note: Calls plotAverageHeatmap with addHeadline=false to avoid subplot-style titles.
    figAvg = figure('Color','w', 'Name', sprintf('Average - %s_%s', group, color));
    plotAverageHeatmap(boundaries, seqTimes, normMatrix, nSessions, false);
    sgtitle(sprintf('%s, %s - Average Only (Outliers |value| > %.1f excluded)', ...
        group, color, 1-threshold), 'FontSize', 12, 'Interpreter', 'none');
end
